### ISSUE TITLE
Cannot authorize the application

### ISSUE THREAD

**Issue by domenic** [9-volt/bug-life#21]
When I try it gets stuck on "Redirecting..." The URL is:

http://9-volt.github.io/bug-life/redirect.html?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=%7B%22client_id%22%3A%22baf32f7bbb8d975e64f3%22%2C%22network%22%3A%22github%22%2C%22display%22%3A%22popup%22%2C%22callback%22%3A%22_hellojs_9xd5nzkc%22%2C%22state%22%3A%22%22%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%2C%22scope%22%3A%22basic%22%2C%22oauth%22%3A%7B%22version%22%3A2%2C%22auth%22%3A%22https%3A%2F%2Fgithub.com%2Flogin%2Foauth%2Fauthorize%22%2C%22grant%22%3A%22https%3A%2F%2Fgithub.com%2Flogin%2Foauth%2Faccess_token%22%2C%22response_type%22%3A%22code%22%7D%7D

**Comment by bumbu** [comment]
I suppose you get this error locally. If so then locally you have to add the auth token manually.

**Comment by domenic** [comment]
No, I got this error on the live version. Don't you?

**Comment by bumbu** [comment]
Worked fine for me on live. 
Locally I get this error but that's because as error states - redirect_uri doesn't match the registered callback uri.

**Comment by domenic** [comment]
Very curious. Can you try https://9-volt.github.io/bug-life/?repo=whatwg/html in an incognito window?

**Comment by bumbu** [comment]
Yep, doesn't work in an incognito window

**Comment by paulmelnikow** [comment]
Same issue here. Setting a personal token manually worked, but authorizing the app did not. This was on https://9-volt.github.io/bug-life/.

<img width="962" alt="screen shot 2017-03-31 at 11 52 36 am" src="https://cloud.githubusercontent.com/assets/1487036/24558282/9c4505b2-1608-11e7-8ec5-acfc8a3c7507.png">

<img width="502" alt="screen shot 2017-03-31 at 11 52 53 am" src="https://cloud.githubusercontent.com/assets/1487036/24558286/a0ae528e-1608-11e7-857b-eff87abdc740.png">

**Comment by paulmelnikow** [comment]
Cool project by the way!

**Comment by bumbu** [comment]
Hi @paulmelnikow, thanks. I'll try to fix this issue.

**Comment by bumbu** [comment]
Apparently 2 things happened:
* Github application was removed (maybe by someone from my org)
* The record on hello.js server got lost

Fixing these 2 (and updating the library) helped to fix it.
Thanks @paulmelnikow and @domenic for raising this

**Comment by paulmelnikow** [comment]
Confirmed fixed! Sweet!
