### ISSUE TITLE
Semicircles not displaying

### ISSUE THREAD

**Issue by joha4270** [9-volt/bug-life#25]
When rendering a repo, the semicircles that display how long each bug lived is gone.

I can reproduce this issue on Chrome 51, Firefox 47 and Edge 38 All on Windows 10 preview

**Comment by bumbu** [comment]
Hey @joha4270 ,
Can you please provide a link with an example?

**Comment by joha4270** [comment]
![image](https://cloud.githubusercontent.com/assets/4454884/18227182/34e91132-721c-11e6-8116-3d3f8017ab09.png)


Chrome console report lots of 
>d3.min.js:formatted:169Error: <circle> attribute cx: Expected length, "NaN".o @ d3.min.js:formatted:169

**Comment by ashl1** [comment]
This is because Chrome removed supports of offsetWidth and offsetHeight (look at jquery/jquery#2889). So [this lines](js/visuals.js#L314-L315) provides ```undefined``` which produce ```NaN``` after ```scale()```

**Comment by joha4270** [comment]
Issue is not isolated to chrome. Here is Edge
![image](https://cloud.githubusercontent.com/assets/4454884/19109567/48da15a4-8af6-11e6-89e1-2298276c8c61.png)


And Firefox
![image](https://cloud.githubusercontent.com/assets/4454884/19109585/584f29c0-8af6-11e6-8811-606ec41a555e.png)

**Comment by ashl1** [comment]
Anyway, the PR is done
@bumbu could your check the PR #26 and merge it if ok?
